application: scripted-rovr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(index.html)?
  static_files: index.html
  upload: index\.html
- url: /script\.js
  static_files: script.js
  upload: script\.js
- url: /style\.css
  static_files: style.css
  upload: style\.css
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
